name: Build recovery on macos

on:
  watch:
    types: [started]

  workflow_dispatch:
        
jobs:
  Build:
    if: github.event.repository.owner.id == github.event.sender.id
    runs-on: macos-10.15

    steps:
    - uses: actions/checkout@v3
    - name: Setup Configuration
      run: |
        echo "MANIFEST=$(cat config.env | grep "MANIFEST" | head -n 1 | cut -d "=" -f 2)" >> $GITHUB_ENV
        echo "MANIFEST_BRANCH=$(cat config.env | grep "MANIFEST_BRANCH" | head -n 1 | cut -d "=" -f 2)" >> $GITHUB_ENV
        echo "DEVICE_TREE=$(cat config.env | grep "DEVICE_TREE" | head -n 1 | cut -d "=" -f 2)" >> $GITHUB_ENV
        echo "DEVICE_TREE_BRANCH=$(cat config.env | grep "DEVICE_TREE_BRANCH" | head -n 1 | cut -d "=" -f 2)" >> $GITHUB_ENV
        echo "DEVICE_PATH=$(cat config.env | grep "DEVICE_PATH" | head -n 1 | cut -d "=" -f 2)" >> $GITHUB_ENV
        echo "MAKEFILE_NAME=$(cat config.env | grep "MAKEFILE_NAME" | head -n 1 | cut -d "=" -f 2)" >> $GITHUB_ENV
        echo "MAKEWHAT=$(cat config.env | grep "MAKEWHAT" | head -n 1 | cut -d "=" -f 2)" >> $GITHUB_ENV


    - name: Prepare Environment
      run: |
        export HOME=${GITHUB_WORKSPACE}
        cd ${GITHUB_WORKSPACE}
        ulimit -S -n 2048
        hdiutil create ~/android.dmg -volname "android" -size 85G -fs "Case-sensitive HFS+"
        hdiutil mount ~/android.dmg
        mkdir -p ${GITHUB_WORKSPACE}/workspace
        ln -s /Volumes/android ${GITHUB_WORKSPACE}/workspace
        echo "DEVICE_NAME=$(echo ${{ env.DEVICE_PATH }} | cut -d'/' -f3)" >> $GITHUB_ENV

    - name: Init Repo
      run: |
        cd ${GITHUB_WORKSPACE}/workspace/android
        mkdir ~/bin
        export PATH=~/bin:$PATH
        curl https://mirrors.tuna.tsinghua.edu.cn/git/git-repo > ~/bin/repo
        chmod a+x ~/bin/repo
        git config --global user.name "Hikaru's Action-Build-Bot"
        git config --global user.email "Android@teio.tk"
        ~/bin/repo init --depth=1 -u ${{ env.MANIFEST }} -b ${{ env.MANIFEST_BRANCH }}
        sed -i "" '/darwin-x86/d' .repo/manifests/remove-minimal.xml

    - name: Repo Sync
      run: |
        cd ${GITHUB_WORKSPACE}/workspace/android
        ~/bin/repo sync -j4
  
    - name: Clone Device Tree
      run: |
        cd ${GITHUB_WORKSPACE}/workspace/android
        git clone ${{ env.DEVICE_TREE }} -b ${{ env.DEVICE_TREE_BRANCH }} ./${{ env.DEVICE_PATH }}
        
    - name: Building recovery
      run: |
        cd ${GITHUB_WORKSPACE}/workspace/android
        . build/envsetup.sh
        lunch ${{ env.MAKEFILE_NAME }}-eng
        echo "BUILD_TIME=$(TZ=Asia/Shanghai date "+%Y%m%d%H%M")" >> $GITHUB_ENV
        mka ${{ env.MAKEWHAT }}image

    - name: Upload ${{ env.MAKEWHAT }} image
      uses: actions/upload-artifact@v3
      with:
        name: ${{ env.MAKEWHAT }}-${{ env.DEVICE_NAME }}-${{ env.BUILD_TIME }}
        path: workspace/android/out/target/product/${{ env.DEVICE_NAME }}/${{ env.MAKEWHAT }}.img
